{
 "title": "singler",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ran_tests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_total{path=\"/ran_tests\"}[1m])"
    }
   ]
  },
  {
   "title": "ran_tests total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_total{path=\"/ran_tests\"}"
    }
   ]
  },
  {
   "title": "create",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_total{path=\"/create\"}[1m])"
    }
   ]
  },
  {
   "title": "create total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_total{path=\"/create\"}"
    }
   ]
  }
 ]
}